function Get-SNOWSCItem {
    <#
    .SYNOPSIS
        Retrieves a sc_cat_item record from SNOW
    .DESCRIPTION
        Gets a record from the sc_cat_item table
    .NOTES
        Uses Get-SNOWObject as a template function.
    .OUTPUTS
        PSCustomObject. The full table record/s.
    .LINK
        https://github.com/insomniacc/PSSnow/blob/main/docs/functions/Get-SNOWSCItem.md
    .LINK
        https://docs.servicenow.com/csh?topicname=c_TableAPI.html&version=latest
    .EXAMPLE
        Get-SNOWSCItem -limit 1 -verbose
        Returns a single record from sc_cat_item
    #>   

    [CmdletBinding()]
    param (
        [Parameter()]
        [string]
        $access_type,
        [Parameter()]
        [boolean]
        $active,
        [Parameter()]
        [string]
        $availability,
        [Parameter()]
        [boolean]
        $billable,
        [Parameter()]
        [string]
        $category,
        [Parameter()]
        [string]
        $checked_out,
        [Parameter()]
        [string]
        $cost,
        [Parameter()]
        [alias('cart')]
        [string]
        $custom_cart,
        [Parameter()]
        [alias('execution_plan')]
        [string]
        $delivery_plan,
        [Parameter()]
        [string]
        $delivery_plan_script,
        [Parameter()]
        [string]
        $delivery_time,
        [Parameter()]
        [string]
        $description,
        [Parameter()]
        [string]
        $display_price_property,
        [Parameter()]
        [string]
        $entitlement_script,
        [Parameter()]
        [alias('flow')]
        [string]
        $flow_designer_flow,
        [Parameter()]
        [string]
        $fulfillment_automation_level,
        [Parameter()]
        [alias('fulfillment_group')]
        [string]
        $group,
        [Parameter()]
        [alias('hide_on_service_portal')]
        [boolean]
        $hide_sp,
        [Parameter()]
        [string]
        $icon,
        [Parameter()]
        [boolean]
        $ignore_price,
        [Parameter()]
        [string]
        $image,
        [Parameter()]
        [string]
        $list_price,
        [Parameter()]
        [string]
        $location,
        [Parameter()]
        [boolean]
        $mandatory_attachment,
        [Parameter()]
        [string]
        $meta,
        [Parameter()]
        [alias('hide_price__mobile_listings_')]
        [boolean]
        $mobile_hide_price,
        [Parameter()]
        [alias('classic_mobile_picture')]
        [string]
        $mobile_picture,
        [Parameter()]
        [alias('classic_mobile_picture_type')]
        [string]
        $mobile_picture_type,
        [Parameter()]
        [string]
        $model,
        [Parameter()]
        [string]
        $name,
        [Parameter()]
        [alias('hide_attachment')]
        [boolean]
        $no_attachment_v2,
        [Parameter()]
        [boolean]
        $no_cart,
        [Parameter()]
        [alias('hide__add_to_cart_')]
        [boolean]
        $no_cart_v2,
        [Parameter()]
        [alias('hide_delivery_time')]
        [boolean]
        $no_delivery_time_v2,
        [Parameter()]
        [boolean]
        $no_order,
        [Parameter()]
        [boolean]
        $no_order_now,
        [Parameter()]
        [boolean]
        $no_proceed_checkout,
        [Parameter()]
        [boolean]
        $no_quantity,
        [Parameter()]
        [alias('hide_quantity')]
        [boolean]
        $no_quantity_v2,
        [Parameter()]
        [boolean]
        $no_search,
        [Parameter()]
        [alias('hide__add_to_wish_list_')]
        [boolean]
        $no_wishlist_v2,
        [Parameter()]
        [alias('omit_price_in_cart')]
        [boolean]
        $omit_price,
        [Parameter()]
        [string]
        $order,
        [Parameter()]
        [string]
        $ordered_item_link,
        [Parameter()]
        [string]
        $owner,
        [Parameter()]
        [string]
        $picture,
        [Parameter()]
        [alias('preview_link')]
        [string]
        $preview,
        [Parameter()]
        [string]
        $price,
        [Parameter()]
        [alias('published_item')]
        [string]
        $published_ref,
        [Parameter()]
        [alias('recurring_price_frequency')]
        [string]
        $recurring_frequency,
        [Parameter()]
        [string]
        $recurring_price,
        [Parameter()]
        [string]
        $request_method,
        [Parameter()]
        [string]
        $roles,
        [Parameter()]
        [alias('catalogs')]
        [string]
        $sc_catalogs,
        [Parameter()]
        [alias('created_from_item_design')]
        [string]
        $sc_ic_item_staging,
        [Parameter()]
        [alias('published_version')]
        [string]
        $sc_ic_version,
        [Parameter()]
        [alias('associated_template')]
        [string]
        $sc_template,
        [Parameter()]
        [string]
        $short_description,
        [Parameter()]
        [alias('expand_help_for_all_questions')]
        [boolean]
        $show_variable_help_on_load,
        [Parameter()]
        [boolean]
        $start_closed,
        [Parameter()]
        [string]
        $state,
        [Parameter()]
        [string]
        $taxonomy_topic,
        [Parameter()]
        [string]
        $template,
        [Parameter()]
        [string]
        $template_manager_roles,
        [Parameter()]
        [string]
        $type,
        [Parameter()]
        [alias('use_cart_layout')]
        [boolean]
        $use_sc_layout,
        [Parameter()]
        [string]
        $vendor,
        [Parameter()]
        [alias('visible_on_bundles')]
        [boolean]
        $visible_bundle,
        [Parameter()]
        [alias('visible_on_guides')]
        [boolean]
        $visible_guide,
        [Parameter()]
        [alias('visible_elsewhere')]
        [boolean]
        $visible_standalone,
        [Parameter()]
        [string]
        $workflow
    )
    DynamicParam { Import-DefaultParamSet -TemplateFunction "Get-SNOWObject" }

    Begin {
        $table = "sc_cat_item"
    }
    Process {
        Invoke-SNOWTableREAD -table $table -Parameters $PSBoundParameters
    }
}

